name: firebase_app_check_example
description: Firebase App Check example application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  cloud_firestore: ^5.5.0
  firebase_app_check: ^0.3.1+6
  firebase_core: ^3.8.0
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
