name: overlay_support
description: provider support for overlay, easy to build toast and internal notification
version: 2.1.0
homepage: https://github.com/boyan01/overlay_support

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  async: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0

flutter:
