name: flutter_staggered_grid_view
description: Provides a collection of Flutter grids layouts (staggered, masonry, quilted, woven, etc.).
version: 0.7.0
homepage: https://github.com/letsar/flutter_staggered_grid_view

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter