name: ntp
description: Fetch accurate time or current DateTime object from (NTP) Network Time Protocol server.
version: 2.0.0
homepage: https://github.com/knezzz/ntp

environment:
  sdk: '>=2.12.0-0 <3.0.0'
