include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print
    - avoid_redundant_argument_values
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_single_quotes
    - require_trailing_commas
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - unnecessary_await_in_return
    - unnecessary_parenthesis
    - use_super_parameters
