name: google_maps_webapi
description: Google Maps Web Services [API](https://developers.google.com/maps/web-services)
version: 0.0.22
homepage: https://github.com/rvndsngwn/google_maps_webapi

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  http: ^1.1.0
  meta: ^1.9.1
  json_annotation: ^4.8.1

dev_dependencies:
  test: ^1.24.3
  lints: ^2.1.1
  build_runner: ^2.4.5
  json_serializable: ^6.7.0
  coverage: ^1.6.3
