name: flutter_emoji
description: "A light-weight Emoji package for Flutter with all up-to-date emojis, made with love and just enjoy!"
version: 2.5.1
homepage: "https://github.com/petehouston/flutter-emoji"

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  characters: ^1.2.0
  http: '>=0.13.0 <2.0.0'

dev_dependencies:
  lint: ^1.0.0
  test: ^1.20.1