name: page_transition
description: Flutter Page Transition Package which is the transition second page
version: 2.1.0
homepage: https://github.com/kalismeras61/flutter_page_transition

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.11.0

flutter:
